version: '3.8'

services:
  redis:
    image: 'redislabs/rejson:2.0.0'
    ports:
      - '6379:6379'
    volumes:
      - 'redisdata:/data'

  server:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    ports:
      - '3000:3001'
    depends_on:
      - redis
    volumes:
      - ./server:/app

  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    ports:
      - '8080:8081'
    depends_on:
      - server
volumes:
  redisdata: